l_polish:
 ADD_CONVEYOR_LINE_BUTTON_DESC:0 "Přidá další jednotku $CONVEYOR|H$, která bude vyrobena paralelně.\n\n§GShift+Click§! pro přidání 5 linek"
 ADD_CONVEYOR_LINE_BUTTON_LABEL:0 "Přidat jednotku"
 AIR_DEPLOYMENT:0 "§TAir Deployment§!"
 CANCEL_CONVEYOR_TOOLTIP:0 "§RCancel§! výrobu všech nasazovacích linek."
 CANNOT_DELETE_SPECIAL_TEMPLATES:0 "Nelze odstranit speciální šablony."
 CANT_CHANGE_DUE_TO_DIVISION_CAP:0 "Nelze změnit na tuto šablonu, protože by to způsobilo, že překročíme náš limit divizí"
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "Nelze změnit na tuto šablonu, protože by to způsobilo, že překročíme náš limit speciálních sil"
 CONVEYOR_CANCEL_DESC:0 "Jste si jisti, že chcete §RCancel§! výrobu všech nasazovacích linek?"
 CONVEYOR_CANCEL_TITLE:0 "§RCancel§! Výroba"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN:0 "§RNot enough manpower to train§!"
 CONVEYOR_CAN_NOT_TRAIN:0 "§RNot enough equipment to train§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§RNot enough manpower or equipment to train $DIVS|H$ of the divisions§!"
 CONVEYOR_COLLAPSE_DESC:0 "§GClick§! pro sbalení"
 CONVEYOR_EQUIPMENT_NEED:0 "Potřeba vybavení:"
 CONVEYOR_EXPAND_DESC:0 "§GClick§! pro rozšíření"
 CONVEYOR_GENERIC_NAME_EDIT_DESC:0 "Napište zde pro změnu obecného názvu nasazení."
 CONVEYOR_GROUP_ASSIGN_DESC:0 "§GClick§! pro přiřazení nasazení k objednávce.\n§GRight-click§! pro resetování přiřazení."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "Nasazení by mělo mít cílové místo, aby bylo možné přidělit k jakékoli skupině."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "Nasazení by mělo mít alespoň jeden příkaz v této oblasti, aby bylo možné přidělit k jakékoli skupině."
 CONVEYOR_HAS_BAD_LOCATION:0 "Cílové místo je §RInvalid§! pro nasazení nyní."
 CONVEYOR_HIGH_PRIORITY_DESC:0 "Vysoká priorita posil"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "Jste si jisti, že chcete §RCancel§! výrobu této nasazovací linky?"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "Jste si jisti, že chcete §RCancel§! výrobu této nasazovací linky?\n(Vyřazení bude také §RRemoved§!)"
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE:0 "§RCancel§! nasazovací linka"
 CONVEYOR_LINE_CANCEL_DESC:0 "§RCancel§! výrobu této linky."
 CONVEYOR_LINE_DEPLOY_DESC:0 "§GClick§! pro okamžité nasazení této linky."
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC:0 "Napište zde pro změnu aktuálního prefixu linky."
 CONVEYOR_LINE_SERIES_BASE:0 "$CURRENT$/$TARGET$"
 CONVEYOR_LOW_PRIORITY_DESC:0 "Nízká priorita posil"
 CONVEYOR_MANPOWER_NEED:0 "Potřeba mužstva: $AMOUNT|H$"
 CONVEYOR_MEDIUM_PRIORITY_DESC:0 "Střední priorita posil"
 CONVEYOR_MOVE_DOWN:0 "§GClick§! k posunutí dolů\n§GShift+Click§! k posunutí na konec"
 CONVEYOR_MOVE_UP:0 "§GClick§! k posunutí nahoru\n§GShift+Click§! k posunutí na začátek"
 CONVEYOR_SERIES_AMOUNT_DESC:0 "To je počet divizí, které každá linka vycvičí před odstraněním.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC:0 "Aktuální sériové číslo nasazení v lince."
 CONVEYOR_SERIES_DECREASE_DESC:0 "Snížení počtu sériového výcviku divizí, které každá linka dokončí.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SERIES_INCREASE_DESC:0 "Zvyšte počet sériového výcviku divizí, které každá linka dokončí.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SET_COLONIAL_LOCATION_DESC:0 "§GClick§! pro nastavení místa nasazení pro toto nasazení.\n§GRight-click§! pro resetování místa.\n§YToto je koloniální šablona a lze ji nasadit pouze v zemi původu!§!"
 CONVEYOR_SET_LOCATION_DESC:0 "§GClick§! pro nastavení místa nasazení pro toto nasazení.\n§GRight-click§! pro resetování místa."
 CONVEYOR_SET_LOCATION_NOT_SET:0 "§RŽádné místo není nastaveno§!"
 CONVEYOR_TEMPLATE_ICON_DESC:0 "Toto nasazení vytváří divize pomocí šablony $TEMPLATE|H$."
 CONVEYOR_TRAINING_NOT_FINISHED:0 " Výcvik této linky ještě není dokončen."
 COPY:0 "Kopírovat"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF:0 "Znovu zařadit"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF_DESC:0 "§GClick§! pro znovu zařazení této šablony, což označí, že je v provozu."
 DECOMMISSION_TEMPLATE_TOGGLE_ON:0 "Vyřadit"
 DECOMMISSION_TEMPLATE_TOGGLE_ON_DESC:0 "§GClick§! pro vyřazení této šablony, což označí, že je vyřazena."
 DELETE_TEMPLATE:0 "§RDelete§! šablonu ze seznamu."
 DELETE_TEMPLATE_DESC:0 "Opravdu chcete tuto šablonu smazat?"
 DELETE_TEMPLATE_TITLE:0 "Smazat šablonu"
 DEPLOY:0 "Nasadit"
 DEPLOYMENT_ADD_TEMPLATE:0 "Trénovat"
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "Nelze trénovat novou divizi speciální šablony."
 DEPLOYMENT_CURRENT_LEVEL:0 "Aktuální úroveň nasazení je $NUMBER$ ( $LEVEL|%Y0$ )"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "Nábor a nasazení"
 DEPLOYMENT_DEPLOY_LABEL:0 "Nasadit"
 DEPLOYMENT_DESIGNER:0 "Návrhář divize"
 DEPLOYMENT_DIVISION_LABEL:0 "Divize"
 DEPLOYMENT_EQUIPMENT:0 "Vybavení: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_CHANGE:0 "$NAME$: $VALUE$"
 DEPLOYMENT_EQUIPMENT_DESC:0 "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC:0 "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT:0 "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL:0 "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "Jako §HGovernment in Exile§! musíme kontrolovat §HCapital§!, abychom mohli trénovat nové divize."
 DEPLOYMENT_EXPERIENCE_DESC:0 "\nPokud je výcvik dokončen, tato jednotka získá dostatečné zkušenosti na to, aby byla nasazena na úroveň $NUMBER$ ( $MAXLEVEL|%Y0$ ) s bojovou modifikací $EFFECT|+=%0$"
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC:0 "\nPokud je tato jednotka plně vybavena, výcvik bude dokončen na §Y$DATE$§!"
 DEPLOYMENT_HIGH_PRIORITY_DESC:0 "Vysoká priorita vybavení"
 DEPLOYMENT_HOW_TO_DESC:0 "Vyberte nasazení(z) ze seznamu a poté §Gclick§! na zvýrazněné provincie na mapě pro nasazení.\n§gJednotky nasazené s neúplným vybavením je získají prostřednictvím žádostí o posily.\nZvažte, že jednotky nasazené příliš raně nedostanou patřičný výcvik.§!"
 DEPLOYMENT_LEND_LEASE_COUNTRY:0 "Lend-Lease: $COUNTRY$"
 DEPLOYMENT_LINES_HIT_THE_CAP:0 "Můžeme vycvičit maximálně $CAP|*H$ mužů.\nOmezeno maximálním počtem dostupných mužů v poli ( $RATIO|H0%$ z $INFIELD|*H$. Minimálně: $MINPOSSIBLE|*H$ mužů)"
 DEPLOYMENT_LINES_HIT_THE_DIVISION_CAP:0 "§RReached the cap for this template§! \n"
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME:0 "§HChoose another historical name.§!\n§GClick§! pro otevření seznamu všech historických jmen, která jsou stále k dispozici. Je možné změnit skupinu jmen úpravou šablony."
 DEPLOYMENT_LINE_EDIT_NAME:0 "§GClick§! a napište, abyste použili vlastní název."
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL:0 "§HErase custom name.§!\nSnažíme se obnovit původně přiřazený název, pokud není již obsazen."
 DEPLOYMENT_LINE_OUT_OF_NAMES:0 "§gOut of historical names.§!"
 DEPLOYMENT_LOW_PRIORITY_DESC:0 "Nízká priorita vybavení"
 DEPLOYMENT_MANPOWER_DESC:0 "Mužstvo: $VALUE|Y0$ ( Max $MAX|Y0$ )"
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "To ponechává místo pro $TRAINABLE|Y$ divizí používajících tuto šablonu."
 DEPLOYMENT_MEDIUM_PRIORITY_DESC:0 "Střední priorita vybavení"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT:0 "Nelze §RDeploy§! jednotku, která nemá žádné vybavení.\nČekejte, dokud toto nasazení nezíská nějaké vybavení."
 DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP:0 "Nelze §RDeploy§! jednotku, která by překročila limit šablony divize"
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER:0 "Nelze §RDeploy§! jednotku, která nemá žádné muže."
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES:0 "Nelze §RDeploy§! jednotku, která by nás překročila limit speciálních sil"
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING:0 "Nelze §RDeploy§! jednotku, která není alespoň $VALUE|1H%$ vycvičena (Aktuálně $CURRENT|1R%$)"
 DEPLOYMENT_PRIORITY_LABEL:0 "Priorita"
 DEPLOYMENT_PROGRESS_LABEL:0 "Pokrok"
 DEPLOYMENT_RAIDS_DESC: "§YÚtoky§!\n§TNastavte prioritu vybavení ve přípravě na útoky§!"
 DEPLOYMENT_RAIDS_EMPTY:0 "§GNo current requests for raids.§!"
 DEPLOYMENT_REMOVE_DIVISION:0 "Zrušit divizi"
 DEPLOYMENT_REQUIREMENT:0 "$NAME$: $AMOUNT$"
 DEPLOYMENT_TEMPLATE_ITEM_ADD:0 "§GClick pro přidání do nasazovací fronty§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY:0 "§GClick pro zkopírování do našich nasaditelných šablon§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§GClick pro úpravu šablony divize§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW:0 "§GClick pro zobrazení šablony divize§!"
 DEPLOYMENT_TEMPLATE_LABEL:0 "Šablony"
 DEPLOYMENT_TRAINING:0 "Vycvičení: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC:0 "/ $VALUE|H%0$ ( Maximální zkušenost nasazení závisí na množství vybavení )"
 DEPLOYMENT_VIEW_SPECIAL_FORCES_DETAILS: "$USED$/$CAP$"
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP:0 "Nemá žádné nasazení připravené k §RDeploy§!."
 DEPLOY_CONVEYOR_TOOLTIP:0 "§GClick§! pro okamžité nasazení všech linek."
 DIVISIONS_QUEUED:0 "$N$ Divizí"
 DIVISION_CAP_LIMIT_DESC:0 "Tato divize využívá limit šablony, protože to je nejnižší limit."
 DIVISION_CAP_OF_TEMPLATE:0 "Tato šablona má limit $NUM|Y$."
 DIVISION_CAP_USAGE_DESC:0 "V současnosti nasazujete $USED|Y$ a školíte $IN_TRAINING|Y$ z našich $CAP|Y$ povolených divizí pro $NAME|Y$"
 DIVISION_DESIGNER_RENAME:0 "Přejmenovat"
 DIVISION_DESIGNER_UPDATE:0 "Aktualizovat"
 DIVISION_EQUIPMENT:1 "Vybavení"
 DIVISION_QUEUED:0 "$N$ Divize"
 DO_NOT_CONTAINS_TEMPLATE:0 "§RCannot delete this Template. Country does not contain this Template.§!"
 EDIT:0 "Upravit"
 EXCEEDING_DIVISION_CAP:0 "§RExceeding cap for division's template§!"
 GARRISONS:0 "Garnizony"
 GARRISONS_DESC:1 "§YGarnizony§!\n§TNastavte prioritu pro vybavení, které jde do garnizonů§!"
 GARRISONS_EMPTY:0 "§GNo current requests for garrisons.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§RCannot delete this Template because $AMOUNT|H$ Division(s) are transitioning from this template to new one (Waiting for receiving equipment matching new template).§!"
 HAS_ARMIES_WITH_TEMPLATE:0 "§RCannot delete this Template because $AMOUNT|H$ Division(s) are using it.§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "Nelze §RRemove§! tuto šablonu ze země. Země má $AMOUNT|H$ nasazení pomocí této šablony."
 HAS_EXILE_TRANSFER_WITH_TEMPLATE: "§RCannot delete this Template because $AMOUNT|H$ Divisions escaping into exile are using it.§!"
 HAS_GARRISON_WITH_TEMPLATE:0 "§RCannot delete this Template because it is being used as Garrison Template for some occupied territories.§!"
 LAND_DEPLOYMENT:0 "§TLand Deployment§!"
 MISSING_SPECIAL_FORCES_CAP:0 "§RNot enough special forces cap§!"
 NAVAL_DEPLOYMENT:0 "§TNaval Deployment§!"
 NEW_EQUIPMENT_ALLOWED:0 "Použijte novou výbavu"
 NEW_GROUP_ADDITIONAL_COST:0 "Nová skupina $VALUE|H0$£army_experience£"
 NO_SPECIAL_FORCES:0 "Tato šablona neobsahuje žádné speciální síly"
 ONLY_ONE_TEMPLATE_LEFT:0 "Nemůžete smazat svou poslední šablonu."
 OPERATIONS_DESC:1 "§YOperace§!\n§TNastavte prioritu pro vybavení ve přípravě a vykonávání operací§!"
 OPERATIONS_EMPTY:0 "§GNo current requests for operations.§!"
 REGIMENTS_SELECTION_CANCEL:0 "Zpět"
 REINFORCEMENT:0 "Posily"
 REINFORCEMENT_DESC:1 "§YPosily§!\n§TNastavte prioritu pro vybavení, které posílí aktivní jednotky ve srovnání s pořadím nasazení a upgrady§!"
 REINFORCEMENT_EMPTY:0 "§GNo current requests for equipment.§!"
 SHOW_DECOMMISSIONED_TEMPLATES:0 "Zobrazit §Hdecommissioned templates§!"
 SPECIAL_FORCES_CAP_DESC:1 "V současnosti nasazujete $USED|Y$ a školíte $IN_TRAINING|Y$ z naší $CAP|Y$ povolené kapacity speciálních sil"
 SPECIAL_FORCES_CAP_LIMIT_DESC:0 "Tato divize využívá limit speciálních sil, protože to je nejnižší limit."
 SPECIAL_FORCES_IN_TEMPLATE:2 "Tento šablonu využívá kapacitu $NUM|Y$ speciálních sil."
 TEMPLATE_PRIO_0:0 "Rezervy"
 TEMPLATE_PRIO_0_DESC:0 "Jednotky s touto šablonou dostanou vybavení jako poslední a s nejnižší prioritou, jakmile budou nasazeny. Perfektní pro jednotky, které chrání základny a podobně."
 TEMPLATE_PRIO_1:0 "Výchozí"
 TEMPLATE_PRIO_1_DESC:0 "Jednotky s touto šablonou získávají průměrnou prioritu pro vybavení a posily po nasazení."
 TEMPLATE_PRIO_2:0 "Elita"
 TEMPLATE_PRIO_2_DESC:0 "Jednotky s touto šablonou dostanou vybavení před každým jiným, jakmile budou nasazeny, a to s nejvyšší prioritou. Použijte pro své nejlepší muže a tam, kde mohou udělat nejvíce dobra."
 TIMED_ACTIVITY_ALERT_TITLE:0 "$NAME|H$ proti $COUNTRY|H$"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC:0 "§GMaximum of equipment was collected.§!"
 TIMED_ACTIVITY_ENTRY_DESC:0 "§TNastavte prioritu pro vybavení, které podpoří tuto diplomatickou činnost.§!"
 TIMED_ACTIVITY_TITLE:0 "$NAME$ proti $COUNTRY$"
 TRAINING_HALTED:0 "Výcvik byl zastaven\n"
 UPGRADES:0 "Vylepšení"
 UPGRADES_DESC:1 "§YUpgrades§!\n§TNastavte prioritu pro vybavení, které jde na upgradování aktivních jednotek ve srovnání s pořadím nasazení a posilami§!"
 UPGRADES_EMPTY:0 "§GNo current requests for upgrade.§!"
 VIEW:0 "Zobrazit"
 group_armor_combat_support_title:0 "Armored Combat Support Battalions"
 group_armor_title:0 "Armored Battalions"
 group_combat_support_title:0 "Bojová podpora"
 group_infantry_title:0 "Infantry Battalions"
 group_mobile_combat_support_title:0 "Mobilní bojová podpora"
 group_mobile_title:0 "Mobilní divize"
 group_support_title:1 "Podpůrné společnosti"
