l_polish:
 ADD_CONVEYOR_LINE_BUTTON_DESC: "Zahájí paralelní výcvik další divize typu $CONVEYOR|H$.\n\n§GShift+klik§! přidá 5 divizí"
 ADD_CONVEYOR_LINE_BUTTON_LABEL: "Přidat divizi"
 AIR_DEPLOYMENT: "§TNasazení letectva§!"
 CANCEL_CONVEYOR_TOOLTIP: "§RZrušit§! výcvik všech divizí."
 CANNOT_DELETE_SPECIAL_TEMPLATES: "Nelze odstranit speciální šablony."
 CANT_CHANGE_DUE_TO_DIVISION_CAP: "Nelze změnit na tuto šablonu — překročilo by to limit počtu divizí."
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP: "Nelze změnit na tuto šablonu — překročilo by to limit speciálních sil."
 CONVEYOR_CANCEL_DESC: "Opravdu chcete §Rzrušit§! výcvik všech divizí ve frontě?"
 CONVEYOR_CANCEL_TITLE: "§RZrušit§! výcvik"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN: "§RNedostatek personálu pro výcvik§!"
 CONVEYOR_CAN_NOT_TRAIN: "§RNedostatek vybavení pro výcvik§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT: "§RNedostatek personálu nebo vybavení pro výcvik $DIVS|H$ divizí§!"
 CONVEYOR_COLLAPSE_DESC: "§GKlikni§! pro sbalení"
 CONVEYOR_EQUIPMENT_NEED: "Požadované vybavení:"
 CONVEYOR_EXPAND_DESC: "§GKlikni§! pro rozbalení"
 CONVEYOR_GENERIC_NAME_EDIT_DESC: "Napište zde pro změnu obecného názvu nasazení."
 CONVEYOR_GROUP_ASSIGN_DESC: "§GKlikni§! pro přiřazení k rozkazu.\n§GPravý klik§! pro zrušení přiřazení."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC: "Nasazení musí mít cílovou lokaci pro přiřazení ke skupině."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC: "Nasazení musí mít alespoň jeden rozkaz v rámci válčiště pro přiřazení ke skupině."
 CONVEYOR_HAS_BAD_LOCATION: "Cílová oblast je nyní §Rneplatná§! pro nasazení."
 CONVEYOR_HIGH_PRIORITY_DESC: "Vysoká priorita doplňování"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC: "Opravdu chceš §Rzrušit§! výcvik této divize?"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC: "Opravdu chceš §Rzrušit§! výcvik této divize?\n(Divize bude také §Rodstraněna§!)"
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE: "§RZrušit§! výcvik"
 CONVEYOR_LINE_CANCEL_DESC: "§RZrušit§! výcvik této divize."
 CONVEYOR_LINE_DEPLOY_DESC: "§GKlikněte§! pro okamžité nasazení této řady" # todo: CHANGED
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC: "Napište zde pro změnu aktuálního prefixu linky."
 CONVEYOR_LINE_SERIES_BASE: "$CURRENT$/$TARGET$"
 CONVEYOR_LOW_PRIORITY_DESC: "Nízká priorita doplňování"
 CONVEYOR_MANPOWER_NEED: "Požadovaný personál: $AMOUNT|H$"
 CONVEYOR_MEDIUM_PRIORITY_DESC: "Střední priorita doplňování"
 CONVEYOR_MOVE_DOWN: "§GKlik§! k posunutí dolů\n§GShift+Klik§! k posunutí na konec"
 CONVEYOR_MOVE_UP: "§GKlik§! k posunutí nahoru\n§GShift+Klik§! k posunutí na začátek"
 CONVEYOR_SERIES_AMOUNT_DESC: "To je počet divizí, které každá linka vycvičí předtím, než bude ukončena.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC: "Aktuální série výcviku divizí v této lince."
 CONVEYOR_SERIES_DECREASE_DESC: "Snížení počtu sériového výcviku divizí, které každá linka dokončí.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SERIES_INCREASE_DESC: "Zvýšení počtu sériového výcviku divizí, které každá linka dokončí.\n\nNastavení na nekonečno znamená, že každá linka vycvičí novou divizi, když je předchozí nasazena."
 CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§GKlik§! pro nastavení místa nasazení pro tuhle divizi ve výcviku.\n§GPravý klik§! pro resetování místa.\n§YToto je koloniální šablona a lze ji nasadit pouze v zemi původu!§!"
 CONVEYOR_SET_LOCATION_DESC: "§GKlik§! pro nastavení místa nasazení pro tuhle divizi ve výcviku.\n§GPravý klik§! pro resetování výběru."
 CONVEYOR_SET_LOCATION_NOT_SET: "§RNevybráno žádné místo§!"
 CONVEYOR_TEMPLATE_ICON_DESC: "Zde probíhá výcvik divizí dle šablony $TEMPLATE|H$."
 CONVEYOR_TRAINING_NOT_FINISHED: " Výcvik této linky ještě není dokončen."
 COPY: "Kopírovat"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF: "Znovuzařadit"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF_DESC: "§GKlikněte§! pro opětovné uvedení této šablony do provozu, označí ji jako v provozu" # todo: CHANGED
 DECOMMISSION_TEMPLATE_TOGGLE_ON: "Vyřadit"
 DECOMMISSION_TEMPLATE_TOGGLE_ON_DESC: "§GKlikněte§! pro vyřazení této šablony, označí ji jako vyřazenou" # todo: CHANGED
 DELETE_TEMPLATE: "§RVymazat§! šablonu ze seznamu."
 DELETE_TEMPLATE_DESC: "Opravdu chcete tuto šablonu smazat?"
 DELETE_TEMPLATE_TITLE: "Smazat šablonu"
 DEPLOY: "Nasadit"
 DEPLOYMENT_ADD_TEMPLATE: "Trénovat"
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS: "Nelze trénovat novou divizi speciálních jednotek."
 DEPLOYMENT_CURRENT_LEVEL: "Aktuálně je divize ve výcviku na úrovni $NUMBER$ ( $LEVEL|%Y0$ )"
 DEPLOYMENT_DEPLOYMENT_LABEL: "Nábor a nasazení"
 DEPLOYMENT_DEPLOY_LABEL: "Nasadit"
 DEPLOYMENT_DESIGNER: "Návrhář divize"
 DEPLOYMENT_DIVISION_LABEL: "Divize"
 DEPLOYMENT_EQUIPMENT: "Vybavení: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_CHANGE: "$NAME$: $VALUE$"
 DEPLOYMENT_EQUIPMENT_DESC: "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC: "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT: "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL: "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL: "Jako §Hexilová vláda§! musíme kontrolovat §Hhlavní město§!, abychom mohli trénovat nové divize."
 DEPLOYMENT_EXPERIENCE_DESC: "\nPokud je výcvik dokončen, tato divize získá dostatečné zkušenosti na to, aby byla nasazena na úrovni $NUMBER$ ( $MAXLEVEL|%Y0$ ) s bojovým modifikátorem $EFFECT|+=%0$"
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC: "\nPokud je tato divize plně vybavena, výcvik bude dokončen §Y$DATE$§!"
 DEPLOYMENT_HIGH_PRIORITY_DESC: "Vysoká priorita vybavení"
 DEPLOYMENT_HOW_TO_DESC: "Vyberte divize ve výcviku ze seznamu a poté §Gklikněte§! na zvýrazněné provincie na mapě pro jejich nasazení.\n§gDivize nasazené s neúplným vybavením je získají prostřednictvím žádostí o posily.\nZvažte, že divize nasazené příliš brzo nedostanou patřičný výcvik.§!"
 DEPLOYMENT_LEND_LEASE_COUNTRY: "Lend-Lease: $COUNTRY$"
 DEPLOYMENT_LINES_HIT_THE_CAP: "Můžeme vycvičit maximálně $CAP|*H$ mužů.\nOmezeno maximálním počtem personálu v poli ( $RATIO|H0%$ z $INFIELD|*H$. Minimálně: $MINPOSSIBLE|*H$ mužů)"
 DEPLOYMENT_LINES_HIT_THE_DIVISION_CAP: "§RDosáhnuto maxima pro tuhle šablonu§! \n"
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME: "§HZvolte další historické jméno.§!\n§GKlikněte§! pro otevření seznamu všech historických jmen, která jsou stále k dispozici. Je možné změnit skupinu jmen úpravou šablony."
 DEPLOYMENT_LINE_EDIT_NAME: "§GKlikněte§! a napište vlastní název" # todo: CHANGED
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL: "§HVymazat vlastní název§!\nSnažíme se obnovit původně přiřazený název, pokud není již obsazen."
 DEPLOYMENT_LINE_OUT_OF_NAMES: "§gNedostatek historických jmen.§!"
 DEPLOYMENT_LOW_PRIORITY_DESC: "Nízká priorita vybavení"
 DEPLOYMENT_MANPOWER_DESC: "Personál: $VALUE|Y0$ ( Max $MAX|Y0$ )"
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE: "To ponechává místo pro $TRAINABLE|Y$ divizí používajících tuto šablonu."
 DEPLOYMENT_MEDIUM_PRIORITY_DESC: "Střední priorita vybavení"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT: "§RNelze§! nasadit divizi, která nemá žádné vybavení.\nPočkejte, dokud tato divize ve výcviku nezíská nějaké vybavení."
 DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP: "§RNelze§! nasadit divizi, která by překročila limit pro danou šablony divize"
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER: "§RNelze§! nasadit divizi, která nemá žádné muže."
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES: "§RNelze§! nasadit divizi, která by překročila náš limit speciálních jednotek"
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING: "Nelze §RNasadit§! jednotku, která není alespoň $VALUE|1H%$ vycvičená (aktuálně $CURRENT|1R%$)" # todo: CHANGED
 DEPLOYMENT_PRIORITY_LABEL: "Priorita"
 DEPLOYMENT_PROGRESS_LABEL: "Pokrok"
 DEPLOYMENT_RAIDS_DESC: "§YNálety§!\n§TNastavte prioritu vybavení pro přípravu náletů§!"
 DEPLOYMENT_RAIDS_EMPTY: "§GŽádna aktuální požadavka pro nálet.§!"
 DEPLOYMENT_REMOVE_DIVISION: "Zrušit divizi"
 DEPLOYMENT_REQUIREMENT: "$NAME$: $AMOUNT$"
 DEPLOYMENT_TEMPLATE_ITEM_ADD: "§GKlikněte pro přidání do fronty pro výcvik§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY: "§GKlikněte pro zkopírování do našich nasaditelných šablon§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT: "§GKlikněte pro úpravu šablony divize§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW: "§GKlikněte pro zobrazení šablony divize§!"
 DEPLOYMENT_TEMPLATE_LABEL: "Šablony divizí" # todo: CHANGED
 DEPLOYMENT_TRAINING: "Výcvik: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC: "/ $VALUE|H%0$ ( Maximální úroveň výcviku závisí na množství vybavení )"
 DEPLOYMENT_VIEW_SPECIAL_FORCES_DETAILS: "$USED$/$CAP$"
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP: "Nemá žádné divize ve výcviku připravené k okamžitému §Rnasazení§!."
 DEPLOY_CONVEYOR_TOOLTIP: "§GKlikněte§! pro okamžité nasazení všech řad" # todo: CHANGED
 DIVISIONS_QUEUED: "Počet divizí: $N$"
 DIVISION_CAP_LIMIT_DESC: "Tato divize využívá limit šablony, protože to je nejnižší limit."
 DIVISION_CAP_OF_TEMPLATE: "Tato šablona má limit na úrovni $NUM|Y$."
 DIVISION_CAP_USAGE_DESC: "V současnosti nasazujete $USED|Y$ a ve výcviku se nachází $IN_TRAINING|Y$ z našich $CAP|Y$ povolených divizí pro $NAME|Y$"
 DIVISION_DESIGNER_RENAME: "Přejmenovat"
 DIVISION_DESIGNER_UPDATE: "Aktualizovat"
 DIVISION_EQUIPMENT: "Vybavení"
 DIVISION_QUEUED: "Počet divizí: $N$"
 DO_NOT_CONTAINS_TEMPLATE: "§RTuto šablonu nelze odstranit. Země ji nevlastní.§!"
 EDIT: "Upravit"
 EXCEEDING_DIVISION_CAP: "§RPřekročena kapacita pro tuto šablonu divize.§!"
 GARRISONS: "Posádky"
 GARRISONS_DESC: "§YPosádky§!\n§TNastavte prioritu vybavení určeného pro posádky§!"
 GARRISONS_EMPTY: "§GAktuálně nejsou žádné požadavky pro posádky.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE: "§RTuto šablonu nelze odstranit, protože $AMOUNT|H$ divizí přechází na novou šablonu (čekají na vybavení odpovídající nové šabloně).§!"
 HAS_ARMIES_WITH_TEMPLATE: "§RTuto šablonu nelze odstranit, protože ji právě používá $AMOUNT|H$ divizí.§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE: "§RNelze odstranit§! tuto šablonu ze země. Země má $AMOUNT|H$ nasazených divizí využívajících tuto šablonu."
 HAS_EXILE_TRANSFER_WITH_TEMPLATE: "§RTuto šablonu nelze odstranit, protože ji používá $AMOUNT|H$ divizí ustupujících do exilu.§!"
 HAS_GARRISON_WITH_TEMPLATE: "§RTuto šablonu nelze odstranit, protože je používána jako šablona posádek pro okupovaná území.§!"
 LAND_DEPLOYMENT: "§TNasazení pozemních sil§!"
 MISSING_SPECIAL_FORCES_CAP: "§RNedostatečná kapacita pro speciální jednotky§!"
 NAVAL_DEPLOYMENT: "§TNasazení námořnictva§!"
 NEW_EQUIPMENT_ALLOWED: "Používat nové vybavení"
 NEW_GROUP_ADDITIONAL_COST: "Nová skupina $VALUE|H0$£army_experience£"
 NO_SPECIAL_FORCES: "Tato šablona neobsahuje žádné speciální jednotky"
 ONLY_ONE_TEMPLATE_LEFT: "Nelze odstranit poslední šablonu."
 OPERATIONS_DESC: "§YOperace§!\n§TUprav prioritu vybavení pro přípravu a provádění operací§!"
 OPERATIONS_EMPTY: "§GAktuálně nejsou žádné požadavky pro operace.§!"
 REGIMENTS_SELECTION_CANCEL: "Zpět"
 REINFORCEMENT: "Posily"
 REINFORCEMENT_DESC: "§YPosily§!\n§TNastavte prioritu pro vybavení, které bude preferovat posily pro divize v terénu oproti výcviku a modernizaci§!"
 REINFORCEMENT_EMPTY: "§GAktuálně nejsou žádné požadavky na vybavení.§!"
 SHOW_DECOMMISSIONED_TEMPLATES: "Zobrazit §Hvyřazené šablony§!"
 SPECIAL_FORCES_CAP_DESC: "V současnosti máme nasazeno $USED|Y$ a ve výcviku $IN_TRAINING|Y$ z povolené kapacity $CAP|Y$ speciálních jednotek."
 SPECIAL_FORCES_CAP_LIMIT_DESC: "Tato divize využívá limit pro speciální jednotky, protože se jedná o nejnižší dostupný limit."
 SPECIAL_FORCES_IN_TEMPLATE: "Tato šablona využívá $NUM|Y$ kapacity speciálních jednotek."
 TEMPLATE_PRIO_0: "Zálohy"
 TEMPLATE_PRIO_0_DESC: "Jednotky s touto šablonou budou po nasazení dostávat vybavení jako poslední s nejnižší prioritou. Vhodné pro jednotky na obranu základen a podobně."
 TEMPLATE_PRIO_1: "Výchozí"
 TEMPLATE_PRIO_1_DESC: "Jednotky s touto šablonou mají po nasazení běžnou prioritu při zásobování a doplňování vybavení."
 TEMPLATE_PRIO_2: "Elita"
 TEMPLATE_PRIO_2_DESC: "Jednotky s touto šablonou budou po nasazení vybaveny přednostně. Použijte je pro své nejlepší muže tam, kde mohou být nejúčinnější."
 TIMED_ACTIVITY_ALERT_TITLE: "$NAME|H$ proti zemi $COUNTRY|H$"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC: "§GBylo získáno maximální množství vybavení.§!"
 TIMED_ACTIVITY_ENTRY_DESC: "§TUrčete prioritu vybavení, které bude použito na podporu této diplomatické aktivity.§!"
 TIMED_ACTIVITY_TITLE: "$NAME$ proti zemi $COUNTRY$"
 TRAINING_HALTED: "Výcvik byl pozastaven\n"
 UPGRADES: "Modernizace"
 UPGRADES_DESC: "§YModernizace§!\n§TNastavte prioritu pro vybavení, které jde na modernizaci aktivních divizí ve srovnání s divizemi ve výcviku a posilami§!"
 UPGRADES_EMPTY: "§GŽádné aktuální požadavky na modernizaci.§!"
 VIEW: "Zobrazit"
 group_armor_combat_support_title: "Obrněné podpůrné prapory"
 group_armor_title: "Obrněné prapory"
 group_combat_support_title: "Bojové podpůrné prapory"
 group_infantry_title: "Pěší prapory"
 group_mobile_combat_support_title: "Mobilní podpůrné prapory"
 group_mobile_title: "Mobilní prapory"
 group_support_title: "Podpůrné roty"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT_HQ: "§GKlikněte pro úpravu šablony velitelství armády§!" # todo: NEW TRANSLATION
 ONLY_ONE_HQ_TEMPLATE_LEFT: "§RNemůžete smazat poslední šablonu velitelství armády.§!" # todo: NEW TRANSLATION
 DEPLOYMENT_CANNOT_TRAIN_HQ: "§RŠablony velitelství armády nelze vycvičit§!, lze je pouze nasadit z armády s §Ypřiděleným velitelem.§!" # todo: NEW TRANSLATION
