name: Len tag

on:
  push:
    tags:
      - '*'

jobs:
  upload_mod:
    runs-on: ubuntu-latest
    env:
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_IP: ${{ secrets.VPS_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      TAG: ${{ github.ref_name }}
    steps:
      - name: Set up SSH
        run: |
          install -m 700 -d ~/.ssh
          printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$VPS_IP" >> ~/.ssh/known_hosts

      - name: Run upload
        run: |
          ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes "$VPS_USER@$VPS_IP" \
            "cd ~/hoi4 && ./venv/bin/python3 kp.py '${TAG}'"
